backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages/"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

