
development_overrides:
  # run file-system backend for local development
  backend:
    name: file-system
    api_root: /api

backend:
  name: git-gateway
  branch: master
#publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages/"
    create: true
    slug: "{{title}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "Page",
        }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Introduction", name: "introduction", widget: "text", required: false}
      - {label: "Hide", name: "hide", widget: "boolean", required: false,  default: false}
      - label: "Blocks"
        name: "blocks"
        widget: "list"
        types: 
          - label: "Hero"
            name: "Hero"
            widget: "object"
            fields:
              - {
                 label: "Full width",
                 name: "full",
                 widget: "hidden",
                 default: true,
                 }
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Introduction", name: "introduction", required: false,  widget: "text"}
              - {label: "Image", name: "image", widget: "image", required: false}
          - label: "List"
            name: "FunctionsList"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Introduction", name: "introduction", required: false,  widget: "text"}
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
                  - {label: "Image", name: "image", widget: "image" }

          - label: "Functions"
            name: "FunctionsBlock"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Introduction", name: "introduction", required: false,  widget: "text"}
              - {label: "Compact", name: "compact", widget: "boolean", required: false, default: false}
              - label: "Link"
                name: "link"
                widget: "object"
                fields:
                  - {label: "Text", name: "text", required: false, widget: "string"}
                  - {label: "Link", name: "link",  required: false, widget: "string"}
                  - {label: "External", name: "ext", widget: "boolean", required: false, default: false}
              - label: "Functions"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", required: false, widget: "text"}
          - label: "Solutions"
            name: "Solutions"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Introduction", name: "introduction", required: false,  widget: "text"}
              - label: "Solutions"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Introduction", name: "introduction", widget: "text", required: false}
                  - {label: "List", name: "description", widget: "text"}
                  - {label: "Active", name: "active", widget: "boolean", required: false,  default: false}
          - label: "Form"
            name: "Form"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Introduction", name: "introduction", required: false,  widget: "text"}
              - {label: "Action text", name: "action", widget: "string"}
              - {label: "Success URL", name: "success", widget: "string"}
              - {label: "Image", name: "image", widget: "image", required: false}
              - label: "Fields"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Name", name: "title", widget: "string"}
                  - {label: "Value", name: "description", widget: "string"}
          - label: "Success"
            name: "Success"
            widget: "object"
            fields:
              - {
              label: "Full width",
              name: "full",
              widget: "hidden",
              default: true,
              }
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Introduction", name: "introduction", required: false,  widget: "text"}
              - {label: "Back text", name: "action", widget: "string"}
              - {label: "Back URL", name: "success", widget: "string"}
              - {label: "Image", name: "image", widget: "image", required: false}
          
            
      - {label: "Body", name: "body", widget: "markdown", required: false}
