backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages/"
    create: true
    slug: "{{title}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "page",
        }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Introduction", name: "introduction", widget: "text", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: "Blocks"
        name: "blocks"
        widget: "list"
        types: 
          - label: "List"
            name: "functionsList"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Introduction", name: "introduction", required: false,  widget: "text"}
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "markdown"}
                  - {label: "Image", name: "image", widget: "image" }

          - label: "Functions"
            name: "functionsBlock"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Introduction", name: "introduction", required: false,  widget: "text"}
              - label: "Link"
                name: "link"
                widget: "object"
                fields:
                  - {label: "Text", name: "text", required: false, widget: "string"}
                  - {label: "Link", name: "link",  required: false, widget: "string"}
                  - {label: "External", name: "ext", widget: "boolean", required: false, default: false}
              - label: "Functions"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", required: false, widget: "markdown"}

          - label: "Compact Functions"
            name: "functionsCompactBlock"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Introduction", name: "introduction",  required: false, widget: "text"}
              - label: "Functions"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Description", name: "description", widget: "markdown"}
                  - label: "Link:"
                    widget: "relation"
                    collection: "pages"
                    searchFields: ["slug"]
                    valueField: "{{slug}}"
                    displayFields: [ "slug"]
          - label: "Solutions"
            name: "solutions"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Introduction", name: "introduction", required: false,  widget: "text"}
              - label: "Solutions"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Introduction", name: "introduction", widget: "text"}
                  - {label: "List", name: "body", widget: "markdown"}
            
